server:
  port: 8080
  tomcat:
      uri-encoding: utf-8
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
      basedir: /usr/local/yealink/data/   #指定目录

spring:
    data:
      elasticsearch:
        cluster-nodes: 127.0.0.1:9300 #格式 ip:端口 多个节点逗号隔开
        cluster-name: elasticsearch

    datasource:
        name: myapp
        url: jdbc:mysql://117.48.197.196:3306/myapp?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    application:
      name: myapp-server

    redis:
      ###redis数据库索引(默认为0)
      database: 0
      host: 117.48.197.196
      port: 6379
      password: foobared
      jedis:
        pool:
          ###连接池最大连接数(使用负值表示没有限制)
          max-active: -1
          ###连接池最大阻塞时间(负值表示没有限制)
          max-wait: -1
          ###连接池的最大空闲连接
          max-idle: 5
          ###连接池的最小空闲连接
          min-idle: 0
      ###连接超时时间(毫秒)
      timeout: 10000

    servlet:
      multipart:
        maxFileSize: 30MB
        maxRequestSize : 300MB

    kafka:
      bootstrap-servers: 114.116.175.209:9092

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql




